(test-begin "srfi-112")

(let ((value (implementation-name)))
  (display "implementation-name: ")
  (write value)
  (newline)
  (test-assert (or (equal? value #f) (string? value))))
(let ((value (implementation-version)))
  (display "implementation-version: ")
  (write value)
  (newline)
  (test-assert (or (equal? value #f) (string? value))))
(let ((value (cpu-architecture)))
  (display "cpu-architecture: ")
  (write value)
  (newline)
  (test-assert (or (equal? value #f) (string? value))))
(let ((value (machine-name)))
  (display "machine-name: ")
  (write value)
  (newline)
  (test-assert (or (equal? value #f) (string? value))))
(let ((value (os-name)))
  (display "os-name: ")
  (write value)
  (newline)
  (test-assert (or (equal? value #f) (string? value))))
(let ((value (os-version)))
  (display "os-version: ")
  (write value)
  (newline)
  (test-assert (or (equal? value #f) (string? value))))
(test-end "srfi-112")
