;;;; SPDX-FileCopyrightText: 2013 John Cowan <cowan@ccil.org>
;;;;
;;;; SPDX-License-Identifier: MIT

;(use test)
;(use srfi-113)
;(use srfi-128)
;(load "../sets/comparators-shim.scm")

;; comparators-shim begin
;;;; SPDX-FileCopyrightText: 2013 John Cowan <cowan@ccil.org>
;;;;
;;;; SPDX-License-Identifier: MIT

;;; Below are some default comparators provided by SRFI-114,
;;; but not SRFI-128, which this SRFI has transitioned to
;;; depend on. See the rationale for SRFI-128 as to why it is
;;; preferred in usage compared to SRFI-114.

;; Most if not all of this code is taken from SRFI-114


;(define string-foldcase string-downcase)

(define (make-comparison=/< = <)
  (lambda (a b)
    (cond
      ((= a b) 0)
      ((< a b) -1)
      (else 1))))

;; Comparison procedure for real numbers only
(define (real-comparison a b)
  (cond
    ((< a b) -1)
    ((> a b) 1)
    (else 0)))

;; Comparison procedure for non-real numbers.
(define (complex-comparison a b)
  (let ((real-result (real-comparison (real-part a) (real-part b))))
    (if (= real-result 0)
      (real-comparison (imag-part a) (imag-part b))
      real-result)))

;(define (number-hash obj) (exact (abs obj)))

(define number-comparator
  (make-comparator number? = complex-comparison number-hash))

(define char-comparison (make-comparison=/< char=? char<?))

;(define (char-hash obj) (abs (char->integer obj)))

(define char-comparator
  (make-comparator char? char=? char-comparison char-hash))

;; Makes a hash function that works vectorwise
(define limit (expt 2 20))

(define (make-vectorwise-hash hash length ref)
  (lambda (obj)
    (let loop ((index (- (length obj) 1)) (result 5381))
      (if (= index 0)
        result
        (let* ((prod (modulo (* result 33) limit))
               (sum (modulo (+ prod (hash (ref obj index))) limit)))
          (loop (- index 1) sum))))))

;(define string-hash (make-vectorwise-hash char-hash string-length string-ref))

(define string-comparison (make-comparison=/< string=? string<?))

(define string-ci-comparison (make-comparison=/< string-ci=? string-ci<?))

(define string-comparator
  (make-comparator string? string=? string-comparison string-hash))

;(define (string-ci-hash obj) (string-hash (string-foldcase obj)))

(define string-ci-comparator
  (make-comparator string? string-ci=? string-ci-comparison string-ci-hash))

(define eq-comparator
  (make-comparator
    (lambda (item) #t)
    eq?
    (lambda (item) #f)
    default-hash))

(define eqv-comparator
  (make-comparator
    (lambda (item) #t)
    eqv?
    (lambda (item) #f)
    default-hash))

(define equal-comparator
  (make-comparator
    (lambda (item) #t)
    equal?
    (lambda (item) #f)
    default-hash))
;; comparators-shim end


(test-begin "srfi-113")

(test-begin "sets")
(define (big x) (> x 5))

(test-begin "sets/simple")
(define nums (set number-comparator))
;; nums is now {}
(define syms (set eq-comparator 'a 'b 'c 'd))
;; syms is now {a, b, c, d}
(define nums2 (set-copy nums))
;; nums2 is now {}
(define syms2 (set-copy syms))
;; syms2 is now {a, b, c, d}
(define esyms (set eq-comparator))
;; esyms is now {}
(test-assert (set-empty? esyms))
(define total 0)
(test-assert (set? nums))
(test-assert (set? syms))
(test-assert (set? nums2))
(test-assert (set? syms2))
(test-assert (not (set? 'a)))
(set-adjoin! nums 2)
(set-adjoin! nums 3)
(set-adjoin! nums 4)
(set-adjoin! nums 4)
;; nums is now {2, 3, 4}
(test-equal 4 (set-size (set-adjoin nums 5)))
(test-equal 3 (set-size nums))
(test-equal 3 (set-size (set-delete syms 'd)))
(test-equal 2 (set-size (set-delete-all syms '(c d))))
(test-equal 4 (set-size syms))
(set-adjoin! syms 'e 'f)
;; syms is now {a, b, c, d, e, f}
(test-equal 4 (set-size (set-delete-all! syms '(e f))))
;; syms is now {a, b, c, d}
(test-equal 0 (set-size nums2))
(test-equal 4 (set-size syms2))
(set-delete! nums 2)
;; nums is now {3, 4}
(test-equal 2 (set-size nums))
(set-delete! nums 1)
(test-equal 2 (set-size nums))
(set! nums2 (set-map number-comparator (lambda (x) (* 10 x)) nums))
;; nums2 is now {30, 40}
(test-assert (set-contains? nums2 30))
(test-assert (not (set-contains? nums2 3)))
(set-for-each (lambda (x) (set! total (+ total x))) nums2)
(test-equal 70 total)
(test-equal 10 (set-fold + 3 nums))
(set! nums (set eqv-comparator 10 20 30 40 50))
;; nums is now {10, 20, 30, 40, 50}
(test-assert
  (set=? nums (set-unfold
                (lambda (i) (= i 0))
                (lambda (i) (* i 10))
                (lambda (i) (- i 1))
                5
                eqv-comparator)))
(test-equal '(a) (set->list (set eq-comparator 'a)))
(set! syms2 (list->set eq-comparator '(e f)))
;; syms2 is now {e, f}
(test-equal 2 (set-size syms2))
(test-assert (set-contains? syms2 'e))
(test-assert (set-contains? syms2 'f))
(list->set! syms2 '(a b))
(test-equal 4 (set-size syms2))
(test-end "sets/simple")

(test-begin "sets/search")
;; FIXME
#;(let ((yam (set char-comparator #\y #\a #\m))
((failure/insert insert ignore) (insert 1))
((failure/ignore insert ignore) (ignore 2))
((success/update element update remove) (update #\b 3))
((success/remove element update remove) (remove 4))
(yam! (set char-comparator #\y #\a #\m #\!))
(bam (set char-comparator #\b #\a #\m))
(ym (set char-comparator #\y #\m)))
(define-values (set1 obj1)
  (set-search! (set-copy yam) #\! failure/insert error))
(test-assert (set=? yam! set1))
(test-equal 1 obj1)
(define-values (set2 obj2)
  (set-search! (set-copy yam) #\! failure/ignore error))
(test-assert (set=? yam set2))
(test-equal 2 obj2)
(define-values (set3 obj3)
  (set-search! (set-copy yam) #\y error success/update))
(test-assert (set=? bam set3))
(test-equal 3 obj3)
(define-values (set4 obj4)
  (set-search! (set-copy yam) #\a error success/remove))
(test-assert (set=? ym set4))
(test-equal 4 obj4))
(test-end "sets/search")

(test-begin "sets/subsets")
(define set2 (set number-comparator 1 2))
(define other-set2 (set number-comparator 1 2))
(define set3 (set number-comparator 1 2 3))
(define set4 (set number-comparator 1 2 3 4))
(define sety (set number-comparator 1 2 4 5))
(define setx (set number-comparator 10 20 30 40))
(test-assert (set=? set2 other-set2))
(test-assert (not (set=? set2 set3)))
(test-assert (not (set=? set2 set3 other-set2)))
(test-assert (set<? set2 set3 set4))
(test-assert (not (set<? set2 other-set2)))
(test-assert (set<=? set2 other-set2 set3))
(test-assert (not (set<=? set2 set3 other-set2)))
(test-assert (set>? set4 set3 set2))
(test-assert (not (set>? set2 other-set2)))
(test-assert (set>=? set3 other-set2 set2))
(test-assert (not (set>=? other-set2 set3 set2)))
(test-assert (not (set<? set2 other-set2)))
(test-assert (not (set<? set2 setx)))
(test-assert (not (set<=? set2 setx)))
(test-assert (not (set>? set2 setx)))
(test-assert (not (set>=? set2 setx)))
(test-assert (not (set<?  set3 sety)))
(test-assert (not (set<=? set3 sety)))
(test-assert (not (set>?  set3 sety)))
(test-assert (not (set>=? set3 sety)))
(test-end "sets/subsets")

(test-begin "sets/ops")
;; Potentially mutable
(let ((abcd (set eq-comparator 'a 'b 'c 'd))
      (efgh (set eq-comparator 'e 'f 'g 'h))
      (abgh (set eq-comparator 'a 'b 'g 'h))
      ;; Never get a chance to be mutated
      (other-abcd (set eq-comparator 'a 'b 'c 'd))
      (other-efgh (set eq-comparator 'e 'f 'g 'h))
      (other-abgh (set eq-comparator 'a 'b 'g 'h))
      (all (set eq-comparator 'a 'b 'c 'd 'e 'f 'g 'h))
      (none (set eq-comparator))
      (ab (set eq-comparator 'a 'b))
      (cd (set eq-comparator 'c 'd))
      (ef (set eq-comparator 'e 'f))
      (gh (set eq-comparator 'g 'h))
      (cdgh (set eq-comparator 'c 'd 'g 'h))
      (abcdgh (set eq-comparator 'a 'b 'c 'd 'g 'h))
      (abefgh (set eq-comparator 'a 'b 'e 'f 'g 'h)))
  (test-assert (set-disjoint? abcd efgh))
  (test-assert (not (set-disjoint? abcd ab)))
  ;; FIXME
  #;(parameterize ((current-test-comparator set=?))
  (test-equal abcd (set-union abcd))
  (test-equal all (set-union abcd efgh))
  (test-equal abcdgh (set-union abcd abgh))
  (test-equal abefgh (set-union efgh abgh))
  (define efgh2 (set-copy efgh))
  (set-union! efgh2)
  (test-equal efgh efgh2)
  (set-union! efgh2 abgh)
  (test-equal abefgh efgh2)
  (test-equal abcd (set-intersection abcd))
  (test-equal none (set-intersection abcd efgh))
  (define abcd2 (set-copy abcd))
  (set-intersection! abcd2)
  (test-equal abcd abcd2)
  (set-intersection! abcd2 efgh)
  (test-equal none abcd2)
  (test-equal ab (set-intersection abcd abgh))
  (test-equal ab (set-intersection abgh abcd))
  (test-equal abcd (set-difference abcd))
  (test-equal cd (set-difference abcd ab))
  (test-equal abcd (set-difference abcd gh))
  (test-equal none (set-difference abcd abcd))
  (define abcd3 (set-copy abcd))
  (set-difference! abcd3)
  (test-equal abcd abcd3)
  (set-difference! abcd3 abcd)
  (test-equal none abcd3)
  (test-equal cdgh (set-xor abcd abgh))
  (test-equal all (set-xor abcd efgh))
  (test-equal none (set-xor abcd other-abcd))
  (define abcd4 (set-copy abcd))
  ;; don't test xor! effect
  (test-equal none (set-xor! abcd4 other-abcd))
  (test-equal "abcd smashed?" other-abcd abcd)
  (test-equal "efgh smashed?" other-efgh efgh)
  (test-equal "abgh smashed?" other-abgh abgh))
)
(test-end "sets/ops")

(test-begin "sets/mismatch")
(let ((nums (set number-comparator 1 2 3))
      (syms (set eq-comparator 'a 'b 'c)))
  (test-error (set=? nums syms))
  (test-error (set<? nums syms))
  (test-error (set<=? nums syms))
  (test-error (set>? nums syms))
  (test-error (set>=? nums syms))
  (test-error (set-union nums syms))
  (test-error (set-intersection nums syms))
  (test-error (set-difference nums syms))
  (test-error (set-xor nums syms))
  (test-error (set-union! nums syms))
  (test-error (set-intersection! nums syms))
  (test-error (set-difference! nums syms))
  (test-error (set-xor! nums syms)))
(test-end "sets/mismatch")

(test-begin "sets/whole")
(let* ((whole (set eqv-comparator 1 2 3 4 5 6 7 8 9 10))
       (whole2 (set-copy whole))
       (whole3 (set-copy whole))
       (whole4 (set-copy whole))
       (bottom (set eqv-comparator 1 2 3 4 5))
       (top (set eqv-comparator 6 7 8 9 10))
       (hetero (set eqv-comparator 1 2 'a 3 4))
       (homo (set eqv-comparator 1 2 3 4 5))
       (bucket (set string-ci-comparator "abc" "def")))
  ;; FIXME
  #;(define-values (topx bottomx)
  (set-partition big whole))
;(set-partition! big whole4)
;;; FIXME
#;(parameterize ((current-test-comparator set=?))
(test-equal top (set-filter big whole))
(test-equal bottom (set-remove big whole))
(set-filter! big whole2)
(test-assert (not (set-contains? whole2 1)))
(set-remove! big whole3)
(test-assert (not (set-contains? whole3 10)))
(test-equal top topx)
(test-equal bottom bottomx)
(test-equal top whole4))
(test-equal 5 (set-count big whole))
(test-equal 'a (set-find symbol? hetero (lambda () (error "wrong" '()))))
(test-error  (set-find symbol? homo (lambda () (error "wrong" '()))))
(test-assert (set-any? symbol? hetero))
(test-assert (set-any? number? hetero))
(test-assert (not (set-every? symbol? hetero)))
(test-assert (not (set-every? number? hetero)))
(test-assert (not (set-any? symbol? homo)))
(test-assert (set-every? number? homo)))
(test-end "sets/whole")

(test-begin "sets/lowlevel")
(let* ((bucket (bag string-ci-comparator "abc" "def"))
       (nums (set number-comparator 1 2 3))
       ;; nums is now {1, 2, 3}
       (nums2 (set-replace nums 2.0))
       (sos (set set-comparator
                 (set equal-comparator '(2 . 1) '(1 . 1) '(0 . 2) '(0 . 0))
                 (set equal-comparator '(2 . 1) '(1 . 1) '(0 . 0) '(0 . 2)))))
  (test-equal string-ci-comparator (set-element-comparator bucket))
  (test-assert (set-contains? bucket "abc"))
  (test-assert (set-contains? bucket "ABC"))
  (test-equal "def" (set-member bucket "DEF" "fqz"))
  (test-equal "fqz" (set-member bucket "lmn" "fqz"))
  ;; nums2 is now {1, 2.0, 3}
  (test-assert (set-any? inexact? nums2))
  (set-replace! nums 2.0)
  ;; nums is now {1, 2.0, 3}
  (test-assert (set-any? inexact? nums))
  (test-equal 1 (set-size sos)))
(test-end "sets/lowlevel")

(test-end "sets")

(test-begin "bags")

(test-begin "bags/simple")
(let* ((nums (bag number-comparator))
       ;; nums is now {}
       (syms (bag eq-comparator 'a 'b 'c 'd))
       ;; syms is now {a, b, c, d}
       (nums2 (bag-copy nums))
       ;; nums2 is now {}
       (syms2 (bag-copy syms))
       ;; syms2 is now {a, b, c, d}
       (esyms (bag eq-comparator))
       (total 0))
  ;; esyms is now {}
  (test-assert (bag-empty? esyms))
  (test-assert (bag? nums))
  (test-assert (bag? syms))
  (test-assert (bag? nums2))
  (test-assert (bag? syms2))
  (test-assert (not (bag? 'a)))
  (bag-adjoin! nums 2)
  (bag-adjoin! nums 3)
  (bag-adjoin! nums 4)
  ;; nums is now {2, 3, 4}
  (test-equal 4 (bag-size (bag-adjoin nums 5)))
  (test-equal 3 (bag-size nums))
  (test-equal 3 (bag-size (bag-delete syms 'd)))
  (test-equal 2 (bag-size (bag-delete-all syms '(c d))))
  (test-equal 4 (bag-size syms))
  (bag-adjoin! syms 'e 'f)
  ;; syms is now {a, b, c, d, e, f}
  (test-equal 4 (bag-size (bag-delete-all! syms '(e f))))
  ;; syms is now {a, b, c, d}
  (test-equal 3 (bag-size nums))
  (bag-delete! nums 1)
  (test-equal 3 (bag-size nums))
  (set! nums2 (bag-map number-comparator (lambda (x) (* 10 x)) nums))
  ;; nums2 is now {20, 30, 40}
  (test-assert (bag-contains? nums2 30))
  (test-assert (not (bag-contains? nums2 3)))
  (bag-for-each (lambda (x) (set! total (+ total x))) nums2)
  (test-equal 90 total)
  (test-equal 12 (bag-fold + 3 nums))
  (set! nums (bag eqv-comparator 10 20 30 40 50))
  ;; nums is now {10, 20, 30, 40, 50}
  (test-assert
    (bag=? nums (bag-unfold
                  (lambda (i) (= i 0))
                  (lambda (i) (* i 10))
                  (lambda (i) (- i 1))
                  5
                  eqv-comparator)))
  (test-equal '(a) (bag->list (bag eq-comparator 'a)))
  (set! syms2 (list->bag eq-comparator '(e f)))
  ;; syms2 is now {e, f}
  (test-equal 2 (bag-size syms2))
  (test-assert (bag-contains? syms2 'e))
  (test-assert (bag-contains? syms2 'f))
  (list->bag! syms2 '(e f))
  ;; syms2 is now {e, e, f, f}
  (test-equal 4 (bag-size syms2)))
(test-end "bags/simple")

(test-begin "bags/search")
;; FIXME
#;(let ((yam (bag char-comparator #\y #\a #\m))
((failure/insert insert ignore)
 (insert 1))
((failure/ignore insert ignore)
 (ignore 2))
((success/update element update remove)
 (update #\b 3))
((success/remove element update remove)
 (remove 4))
(yam! (bag char-comparator #\y #\a #\m #\!))
(bam (bag char-comparator #\b #\a #\m))
(ym (bag char-comparator #\y #\m)))
(define-values (bag1 obj1)
  (bag-search! (bag-copy yam) #\! failure/insert error))
(test-assert (bag=? yam! bag1))
(test-equal 1 obj1)
(define-values (bag2 obj2)
  (bag-search! (bag-copy yam) #\! failure/ignore error))
(test-assert (bag=? yam bag2))
(test-equal 2 obj2)
(define-values (bag3 obj3)
  (bag-search! (bag-copy yam) #\y error success/update))
(test-assert (bag=? bam bag3))
(test-equal 3 obj3)
(define-values (bag4 obj4)
  (bag-search! (bag-copy yam) #\a error success/remove))
(test-assert (bag=? ym bag4))
(test-equal 4 obj4))
(test-end "bags/search")

(test-begin "bags/elemcount")
(let ((mybag (bag eqv-comparator 1 1 1 1 1 2 2))
      (bag2 (bag number-comparator 1 2))
      (other-bag2 (bag number-comparator 1 2))
      (bag3 (bag number-comparator 1 2 3))
      (bag4 (bag number-comparator 1 2 3 4))
      (bagx (bag number-comparator 10 20 30 40))
      (bagy (bag number-comparator 10 20 20 30 40)))
  (test-equal 5 (bag-element-count mybag 1))
  (test-equal 0 (bag-element-count mybag 3))
  (test-end "bags/elemcount")

  (test-begin "bags/subbags")
  (test-assert (bag=? bag2 other-bag2))
  (test-assert (not (bag=? bag2 bag3)))
  (test-assert (not (bag=? bag2 bag3 other-bag2)))
  (test-assert (bag<? bag2 bag3 bag4))
  (test-assert (not (bag<? bag2 other-bag2)))
  (test-assert (bag<=? bag2 other-bag2 bag3))
  (test-assert (not (bag<=? bag2 bag3 other-bag2)))
  (test-assert (bag>? bag4 bag3 bag2))
  (test-assert (not (bag>? bag2 other-bag2)))
  (test-assert (bag>=? bag3 other-bag2 bag2))
  (test-assert (not (bag>=? other-bag2 bag3 bag2)))
  (test-assert (not (bag<? bag2 other-bag2)))
  (test-assert (bag<=? bagx bagy))
  (test-assert (not (bag<=? bagy bagx)))
  (test-assert (bag<? bagx bagy))
  (test-assert (not (bag<? bagy bagx)))
  (test-assert (bag>=? bagy bagx))
  (test-assert (not (bag>=? bagx bagy)))
  (test-assert (bag>? bagy bagx))
  (test-assert (not (bag>? bagx bagy))))
(test-end "bags/subbags")

(test-begin "bags/multi")
(define one (bag eqv-comparator 10))
(define two (bag eqv-comparator 10 10))
(test-assert (not (bag=? one two)))
(test-assert (bag<? one two))
(test-assert (not (bag>? one two)))
(test-assert (bag<=? one two))
(test-assert (not (bag>? one two)))
(test-assert (bag=? two two))
(test-assert (not (bag<? two two)))
(test-assert (not (bag>? two two)))
(test-assert (bag<=? two two))
(test-assert (bag>=? two two))
(test-equal '((10 . 2))
            (let ((result '()))
              (bag-for-each-unique
                (lambda (x y) (set! result (cons (cons x y) result)))
                two)
              result))
(test-equal 25 (bag-fold + 5 two))
(test-equal 12 (bag-fold-unique (lambda (k n r) (+ k n r)) 0 two))
(test-end "bags/multi")

(test-begin "bags/ops")
;; Potentially mutable
(define abcd (bag eq-comparator 'a 'b 'c 'd))
(define efgh (bag eq-comparator 'e 'f 'g 'h))
(define abgh (bag eq-comparator 'a 'b 'g 'h))
;; Never get a chance to be mutated
(define other-abcd (bag eq-comparator 'a 'b 'c 'd))
(define other-efgh (bag eq-comparator 'e 'f 'g 'h))
(define other-abgh (bag eq-comparator 'a 'b 'g 'h))
(define all (bag eq-comparator 'a 'b 'c 'd 'e 'f 'g 'h))
(define none (bag eq-comparator))
(define ab (bag eq-comparator 'a 'b))
(define cd (bag eq-comparator 'c 'd))
(define ef (bag eq-comparator 'e 'f))
(define gh (bag eq-comparator 'g 'h))
(define cdgh (bag eq-comparator 'c 'd 'g 'h))
(define abcdgh (bag eq-comparator 'a 'b 'c 'd 'g 'h))
(define abefgh (bag eq-comparator 'a 'b 'e 'f 'g 'h))
(test-assert (bag-disjoint? abcd efgh))
(test-assert (not (bag-disjoint? abcd ab)))
;;FIXME
#;(parameterize ((current-test-comparator bag=?))
(test-equal abcd (bag-union abcd))
(test-equal all (bag-union abcd efgh))
(test-equal abcdgh (bag-union abcd abgh))
(test-equal abefgh (bag-union efgh abgh))
(define efgh2 (bag-copy efgh))
(bag-union! efgh2)
(test-equal efgh efgh2)
(bag-union! efgh2 abgh)
(test-equal abefgh efgh2)
(test-equal abcd (bag-intersection abcd))
(test-equal none (bag-intersection abcd efgh))
(define abcd2 (bag-copy abcd))
(bag-intersection! abcd2)
(test-equal abcd abcd2)
(bag-intersection! abcd2 efgh)
(test-equal none abcd2)
(test-equal ab (bag-intersection abcd abgh))
(test-equal ab (bag-intersection abgh abcd))
(test-equal abcd (bag-difference abcd))
(test-equal cd (bag-difference abcd ab))
(test-equal abcd (bag-difference abcd gh))
(test-equal none (bag-difference abcd abcd))
(define abcd3 (bag-copy abcd))
(bag-difference! abcd3)
(test-equal abcd abcd3)
(bag-difference! abcd3 abcd)
(test-equal none abcd3)
(test-equal cdgh (bag-xor abcd abgh))
(test-equal all (bag-xor abcd efgh))
(test-equal none (bag-xor abcd other-abcd))
(define abcd4 (bag-copy abcd))
(test-equal none (bag-xor! abcd4 other-abcd))
(define abab (bag eq-comparator 'a 'b 'a 'b))
(test-equal ab (bag-sum ab))
(define ab2 (bag-copy ab))
(test-equal ab (bag-sum! ab2))
(test-equal abab (bag-sum! ab2 ab))
(test-equal abab ab2)
(test-equal abab (bag-product 2 ab))
(define ab3 (bag-copy ab))
(bag-product! 2 ab3)
(test-equal abab ab3)
(test-equal "abcd smashed?" other-abcd abcd)
(test-equal "abcd smashed?" other-abcd abcd)
(test-equal "efgh smashed?" other-efgh efgh)
(test-equal "abgh smashed?" other-abgh abgh))
(test-end "bags/ops")

(test-begin "bags/mismatch")
(let ((nums (bag number-comparator 1 2 3))
      (syms (bag eq-comparator 'a 'b 'c)))
  (test-error (bag=? nums syms))
  (test-error (bag<? nums syms))
  (test-error (bag<=? nums syms))
  (test-error (bag>? nums syms))
  (test-error (bag>=? nums syms))
  (test-error (bag-union nums syms))
  (test-error (bag-intersection nums syms))
  (test-error (bag-difference nums syms))
  (test-error (bag-xor nums syms))
  (test-error (bag-union! nums syms))
  (test-error (bag-intersection! nums syms))
  (test-error (bag-difference! nums syms)))
(test-end "bags/mismatch")

(test-begin "bags/whole")
(define whole (bag eqv-comparator 1 2 3 4 5 6 7 8 9 10))
(define whole2 (bag-copy whole))
(define whole3 (bag-copy whole))
(define whole4 (bag-copy whole))
(define bottom (bag eqv-comparator 1 2 3 4 5))
(define top (bag eqv-comparator 6 7 8 9 10))
;; FIXME
#;(define-values (topx bottomx)
(bag-partition big whole))
;(bag-partition! big whole4)
;;;FIXME
#;(parameterize ((current-test-comparator bag=?))
(test-equal top (bag-filter big whole))
(test-equal bottom (bag-remove big whole))
(bag-filter! big whole2)
(test-assert (not (bag-contains? whole2 1)))
(bag-remove! big whole3)
(test-assert (not (bag-contains? whole3 10)))
(test-equal top topx)
(test-equal bottom bottomx)
(test-equal top whole4))
(test-equal 5 (bag-count big whole))
(define hetero (bag eqv-comparator 1 2 'a 3 4))
(define homo (bag eqv-comparator 1 2 3 4 5))
(test-equal 'a (bag-find symbol? hetero (lambda () (error "wrong" '()))))
(test-error  (bag-find symbol? homo (lambda () (error "wrong" '()))))
(test-assert (bag-any? symbol? hetero))
(test-assert (bag-any? number? hetero))
(test-assert (not (bag-every? symbol? hetero)))
(test-assert (not (bag-every? number? hetero)))
(test-assert (not (bag-any? symbol? homo)))
(test-assert (bag-every? number? homo))
(test-end "bags/whole")

(test-begin "bags/lowlevel")
(define bucket (bag string-ci-comparator "abc" "def"))
(test-equal string-ci-comparator (bag-element-comparator bucket))
(test-assert (bag-contains? bucket "abc"))
(test-assert (bag-contains? bucket "ABC"))
(test-equal "def" (bag-member bucket "DEF" "fqz"))
(test-equal "fqz" (bag-member bucket "lmn" "fqz"))
(let* ((nums (bag number-comparator 1 2 3))
       ;; nums is now {1, 2, 3}
       (nums2 (bag-replace nums 2.0))
       (bob (bag bag-comparator
                 (bag eqv-comparator 1 2)
                 (bag eqv-comparator 1 2))))
  ;; nums2 is now {1, 2.0, 3}
  (test-assert (bag-any? inexact? nums2))
  (bag-replace! nums 2.0)
  ;; nums is now {1, 2.0, 3}
  (test-assert (bag-any? inexact? nums))
  (test-equal 2 (bag-size bob)))
(test-end "bags/lowlevel")


(test-begin "bags/semantics")
(define mybag (bag number-comparator 1 2))
;; mybag is {1, 2}
(test-equal 2 (bag-size mybag))
(bag-adjoin! mybag 1)
;; mybag is {1, 1, 2}
(test-equal 3 (bag-size mybag))
(test-equal 2 (bag-unique-size mybag))
(bag-delete! mybag 2)
;; mybag is {1, 1}
(bag-delete! mybag 2)
(test-equal 2 (bag-size mybag))
(bag-increment! mybag 1 3)
;; mybag is {1, 1, 1, 1, 1}
(test-equal 5 (bag-size mybag))
(test-assert (bag-decrement! mybag 1 2))
;; mybag is {1, 1, 1}
(test-equal 3 (bag-size mybag))
(bag-decrement! mybag 1 5)
;; mybag is {}
(test-equal 0 (bag-size mybag))
(test-end "bags/semantics")

(test-begin "bags/convert")
(define multi (bag eqv-comparator 1 2 2 3 3 3))
(define single (bag eqv-comparator 1 2 3))
(define singleset (set eqv-comparator 1 2 3))
(define minibag (bag eqv-comparator 'a 'a))
(define alist '((a . 2)))
(test-equal alist (bag->alist minibag))
(test-assert (bag=? minibag (alist->bag eqv-comparator alist)))
(test-assert (set=? singleset (bag->set single)))
(test-assert (set=? singleset (bag->set multi)))
(test-assert (bag=? single (set->bag singleset)))
(test-assert (not (bag=? multi (set->bag singleset))))
(set->bag! minibag singleset)
;; minibag is now {a, a, a, a, 1, 2, 3}
(test-assert (bag-contains? minibag 1))
(test-end "bags/convert")

(test-begin "bags/sumprod")
(let* ((abb (bag eq-comparator 'a 'b 'b))
       (aab (bag eq-comparator 'a 'a 'b))
       (total (bag-sum abb aab))
       (bag1 (bag eqv-comparator 1)))
  (test-equal 3 (bag-count (lambda (x) (eqv? x 'a)) total))
  (test-equal 3 (bag-count (lambda (x) (eqv? x 'b)) total))
  (test-equal 12 (bag-size (bag-product 2 total)))
  (bag-sum! bag1 bag1)
  (test-equal 2 (bag-size bag1))
  (bag-product! 2 bag1)
  (test-equal 4 (bag-size bag1)))
(test-end "bags/sumprod")

(test-end "bags")

(test-begin "comparators")
(define a (set number-comparator 1 2 3))
(define b (set number-comparator 1 2 4))
(define aa (bag number-comparator 1 2 3))
(define bb (bag number-comparator 1 2 4))
(test-assert (not (=? set-comparator a b)))
(test-assert (=? set-comparator a (set-copy a)))
(test-error (<? set-comparator a b))
(test-assert (not (=? bag-comparator aa bb)))
(test-assert (=? bag-comparator aa (bag-copy aa)))
(test-error (<? bag-comparator aa bb))
(test-assert (not (=? (make-default-comparator) a aa)))
(test-end "comparators")

(test-end "srfi-113")
